<link rel="stylesheet" href="<?php echo public_path;?>/css/index-admin.css">


<div class="container">
	<div class="col-md-12">
	<div class="row">
		<div class="col-md-4">
			<nav class="table-admin"><span class="glyphicon"></span><span class="tieu-de">Table Film</span>
			    <ul>

			        <li><a href="?controller=admin-film&action=index">Danh sách film</a></li>
			        <li><a href="?controller=admin-film&action=add">Thêm film</a></li>
			        

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Danh Mục</span>
			    <ul>

			        <li><a href="?controller=admin-danh-muc&action=index">Danh sách danh mục</a></li>
			        <li><a href="?controller=admin-danh-muc&action=add">Thêm danh mục</a></li>
			        
			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Thể Loại</span>
			    <ul>

			        <li><a href="?controller=admin-the-loai&action=index">Danh sách thể loại</a></li>
			        <li><a href="?controller=admin-the-loai&action=add">Thêm thể loại</a></li>
			        

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Diễn Viên</span>
			    <ul>

			        <li><a href="?controller=admin-dien-vien&action=index">Danh diễn viên</a></li>
			        <li><a href="?controller=admin-dien-vien&action=add">Thêm diễn viên</a></li>
			        

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Đạo Diễn</span>
			    <ul>

			        <li><a href="?controller=admin-dao-dien&action=index">Danh sách đạo diễn</a></li>
			        <li><a href="?controller=admin-dao-dien&action=add">Thêm đạo diễn</a></li>
			        

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Quốc Gia</span>
			    <ul>

			        <li><a href="?controller=admin-quoc-gia&action=index">Danh quốc gia</a></li>
			        <li><a href="?controller=admin-quoc-gia&action=add">Thêm quốc gia</a></li>
			       

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Năm Phát Hành</span>
			    <ul>

			        <li><a href="?controller=admin-nam-phat-hanh&action=index">Danh sách năm phát hành</a></li>
			        <li><a href="?controller=admin-nam-phat-hanh&action=add">Thêm năm phát hành</a></li>
			        
			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table Người Dùng</span>
			    <ul>

			        <li><a href="?controller=admin-nguoi-dung&action=index">Danh sách tài khoản</a></li>
			        <li><a href="?controller=admin-nguoi-dung&action=add">Thêm tài khoản</a></li>
			        

			    </ul>
			</nav>
		</div>
		<div class="col-md-4">
			<nav class="table-admin"><span class="tieu-de">Table User Admin</span>
			    <ul>

			        <li><a href="?controller=admin-user&action=index">Danh sách </a></li>
			        <li><a href="?controller=admin-user&action=add">Thêm account</a></li>
			        

			    </ul>
			</nav>
		</div>
	</div>
</div>
</div>


	

	