<div class="container">
<h1>Thêm mới phim</h1>
<?php
$myText = (string)@$this->view->msg;
if (@$_POST['submit'] == 'thêm mới')
    echo "<script type='text/javascript'>alert('$myText');
    window.location.replace('?controller=admin-tap-film');</script>";
?>

<form action="" method="post">
  <table>
  <tr>
      <td>Tên Film:</td>
      <td><select class="form-control select2" style="width: 100%;" name="txt_ten_film">
        <?php
         foreach ($this->view->film as $row ){
                       echo "
                   <option value='{$row['id']}'>{$row['ten_film']}</option>
                   ";
                   }
                   ?>
        </select>

      </td>
    </tr>
    <tr>
      <td>Tên Tập:</td>
      <td><input type="text" placeholder=" Tên Tập" name="txt_ten_tap"></td>
    </tr>
    <tr>
      <td>Link FB:</td>
      <td>
        <input type="text" placeholder=" Link FB" name="txt_link_fb">
      </td>
    </tr>    
    <tr>
      <td>Link GD:</td>
      <td><input type="text" placeholder=" Link gd" name="txt_link_gd" ></td>
    </tr>
     <tr>
      <td>Link OP:</td>
      <td><input type="text" placeholder=" Link OP" name="txt_link_op"></td>
    </tr>
       <tr>
           <td colspan="2" align="center"><input type="submit" name="submit" value="thêm mới"></td>
       </tr>

   </table>


</form>
</div>