
<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title"><?php echo  $this->view->title; ?></h3>
              <a href="?controller=admin-the-loai&action=add">Thêm mới</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                    <tr>
                                <th>ID</th>
                                <th>Tên Thể Loại</th>
                                <th>Ngày thêm</th>
                                <th>Ngày Cập Nhập</th>


                        </tr>
                </thead>
                <tbody>
                    <?php
                            foreach($this->view->list as $row){

                                $link_edit = "<a href='?controller=admin-the-loai&action=edit&id={$row['id']}'>{$row['ten_the_loai']}</a>";
                                    echo " <tr>
                                                    <td>{$row['id']}</td>
                                                    <td>{$link_edit}</td>
                                                    <td>{$row['ngay_them']}</td>
                                                    <td>{$row['ngay_cap_nhap']}</td>
                                                </tr>";
                            }

                            ?>
                </tbody>
                
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>


