<div class="container">
<h1>Thêm mới danh mục</h1>
<?php
echo @$this->view->msg;
?>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<form action="" method="post">
     <div class="col-md-6">
                <div class="form-group">
                  <table>
                  <tr>
                  <td><select class="form-control select2" style="width:100%;" name="txt_ten_film">
                      <?php
                               foreach ($this->view->film as $row ){
                                   echo "
                                   <option value='{$row['id']}'>{$row['ten_film']}</option>
                                   ";
                               }
                        ?>
                  </select></td>


                  <td><select  name="txt_ten_danh_muc">
                      <?php
                               foreach ($this->view->danh_muc as $row ){
                                   echo "
                                   <option value='{$row['id']}'>{$row['ten_danh_muc']}</option>
                                   ";
                               }
                        ?>
                    </select></td>
                  </tr>
                  </table>
                </div>
                
                <!-- /.form-group -->
                  <input type="submit" name="submit">
                <!-- /.form-group -->
              </div>
     
    
    

</form>
</div>
