<div class="container">
<h1>Chỉnh sửa chi tiết</h1>
<?php
$myText = (string)@$this->view->msg;
// if(isset($this->view->objF->error))
// {
//     echo $this->view->objF->error;
//     return;
// }

if (@$_POST['submit'] == 'update')
    echo "<script type='text/javascript'>alert('$myText');
    window.location.replace('?controller=admin-chi-tiet-danh-muc');</script>";
if(isset($this->view->objDMCT->error))
{
    echo $this->view->objDMCT->error;
    return;
}
$obj = $this->view->objDMCT;
?>


<form action="" method="post">
    <input type="text" name="txt_ten_film" value="<?php echo $obj->ten_film; ?>" readonly></td>
    <select name="txt_ten_danh_muc">
    	<?php
               foreach ($this->view->danh_muc as $row ){
				if($row['id']==$obj->id_danh_muc)

               	echo "
                   <option selected value='{$row['id']}'>{$row['ten_danh_muc']}</option>
                   ";
                   else

                   echo "
                   <option value='{$row['id']}'>{$row['ten_danh_muc']}</option>
                   ";
               }
        ?>
    </select>
    <input type="submit" name="submit" value="update">

</form>
</div>