<?php
$link_public = public_path;
$phim = thong_tin_phim_path;
$base_url = base_url;
if(isset($_GET['search_ten_film']) && strlen($_GET['search_ten_film']) > 0){
   echo '<link rel="stylesheet" href="'.$link_public.'/css/phan_trang.css">
<section class="movie">
    <div class="container">
        <div class="wrap-item">';
            echo "<div class='title-section'>
          <span>
          <a href='' class='see-more'>";
              //$my_title = (string)$this->view->ten_quoc_gia;
          if (isset($_GET['search_ten_film'])) {
              echo "Từ khóa :".$_GET['search_ten_film'];
          }
          echo "     </a>
</span>
</div>
<div class='mv-group'>";


    foreach ($this->view->search as $row){
        $ten_film = ConvertKhongDau($row['ten_film']);
        $ten_film_english = ConvertKhongDau($row['ten_film_english']);
        echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']} - {$row['ten_film_english']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='$base_url/publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}


echo '</div>
</div>
</div>
</section>
<div class="pagination">';

    //hiển thị phần phân trang
    // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
    $data = '';
    if ($this->view->current_page > 1 && $this->view->total_page > 1){
        $data .= '<a class="phan_trang" href="'.$base_url.'/phim-bo/page-'.($this->view->current_page-1).'/">Prev</a>';
    }

    // Lặp khoảng giữa

    $data .=($this->view->current_page - 2) > 1 ? '<li class="phan_trang">...</li>' :'';
    for($i = ($this->view->current_page - 2) > 0 ? ($this->view->current_page - 2) : 1; $i <= (($this->view->current_page + 2) > $this->view->total_page ? $this->view->total_page :($this->view->current_page + 2)); $i++){
        if($i == $this->view->current_page){
            $data .= '<span class="phan_trang" style="background-color: white;color: black">'.$i.'</span>';
        } else{
            $data .= '<a class="phan_trang" href="'.$base_url.'/phim-bo/page-'.$i.'/">'.$i.'</a>';
        }
    }
    $data .=($this->view->current_page + 2) < $this->view->total_page ? '<li class="phan_trang">...</li>' :'';

    // nếu current_page < $this->view->total_page và total_page > 1 mới hiển thị nút prev
    if ($this->view->current_page < $this->view->total_page && $this->view->total_page > 1){
        $data .= '<a class="phan_trang" href="'.$base_url.'/phim-bo/page-'.($this->view->current_page+1).'/">Next</a>';
    }
    echo $data."</div>";


}else{
echo '<meta charset="utf-8">
<!-- slider -->
<script type="text/javascript" src="'.$link_public.'/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="'.$link_public.'/js/jssor.slider.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {

        var jssor_1_options = {
            $AutoPlay: 1,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$,
                $ChanceToShow: 1
            },
            $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $ChanceToShow: 2,
                $ActionMode: 3,
                $Rows: 1,
                $SpacingX: 10,
                $SpacingY: 10
            }
        };

        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

        /*#region responsive code begin*/

        var MAX_WIDTH = 3000;

        function ScaleSlider() {
            var containerElement = jssor_1_slider.$Elmt.parentNode;
            var containerWidth = containerElement.clientWidth;

            if (containerWidth) {

                var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                jssor_1_slider.$ScaleWidth(expectedWidth);
            }
            else {
                window.setTimeout(ScaleSlider, 30);
            }
        }

        ScaleSlider();

        $(window).bind("load", ScaleSlider);
        $(window).bind("resize", ScaleSlider);
        $(window).bind("orientationchange", ScaleSlider);
        /*#endregion responsive code end*/
    });
</script>
<style>
    /*jssor slider loading skin spin css*/
    .jssorl-009-spin img {
        animation-name: jssorl-009-spin;
        animation-duration: 1.6s;
        animation-iteration-count: infinite;
        animation-timing-function: linear;
    }

    @keyframes jssorl-009-spin {
        from { transform: rotate(0deg); }
        to { transform: rotate(360deg); }
    }

    /*jssor slider bullet skin 032 css*/
    .jssorb032 {position:absolute;}
    .jssorb032 .i {position:absolute;cursor:pointer;}
    .jssorb032 .i .b {fill:#09ff23;fill-opacity:0.5;stroke-miterlimit:10;stroke-opacity:0.5;}
    .jssorb032 .i:hover .b {fill: #ff3333;;fill-opacity:1;}
    .jssorb032 .iav .b {fill: #e50000;;fill-opacity:.6;}
    .jssorb032 .i.idn {opacity:.3;}

    /*jssor slider arrow skin 051 css*/
    .jssora051 {display:block;position:absolute;cursor:pointer;}
    .jssora051 .a {fill:none;stroke:#fff;stroke-width:360;stroke-miterlimit:10;}
    .jssora051:hover {opacity:.8;}
    .jssora051.jssora051dn {opacity:.5;}
    .jssora051.jssora051ds {opacity:.3;pointer-events:none;}
</style>
<div style="/*margin-top: 50px*/">
    <div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:1300px;height:480px;overflow:hidden;visibility:hidden;">
        <!-- Loading Screen -->
        <!--<div data-u="loading" class="jssorl-009-spin" style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
            <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="../svg/loading/static-svg/spin.svg" />
        </div>-->
        <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:1300px;height:500px;overflow:hidden;">';
            


            foreach ($this->view->slide as $row){
                $ten_film = ConvertKhongDau($row['ten_film']);
                $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                echo "<a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/'>
                <img data-u='image' src='{$row['link_slide']}' />
            </a>";
            }

     echo '   </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb032" style="position:absolute;bottom:12px;right:12px;" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
            <div data-u="prototype" class="i" style="width:16px;height:16px;">
                <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                    <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                </svg>
            </div>
        </div>
        <!-- Arrow Navigator -->
        <div data-u="arrowleft" class="jssora051" style="width:65px;height:65px;top:0px;left:25px;" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
            <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
            </svg>
        </div>
        <div data-u="arrowright" class="jssora051" style="width:65px;height:65px;top:0px;right:25px;" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
            <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
            </svg>
        </div>
    </div>
</div>
<!-- end slider -->
<main>
  <section class="movie">
        <div class="container">
            <div class="wrap-item">';
     echo "           <div class='title-section'>
          <span>
          <a href='$base_url/phim-bo/' class='see-more'>Phim Bộ mới nhất</a>
          </span>
                    <a href='$base_url/phim-bo/' class='read-more'>xem Thêm >></a>
                </div>
                <div class='mv-group'>";
                    foreach ($this->view->phim_bo as $row){
                        $ten_film = ConvertKhongDau($row['ten_film']);
                    $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                    echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']} - {$row['ten_film_english']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='$base_url/publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}

         echo '</div>
            </div>
        </div>
    </section>
    <section class="movie">
        <div class="container">
            <div class="wrap-item">';
       echo" <div class='title-section'>
          <span>
          <a href='$base_url/phim-le/' class='see-more'>Phim lẻ mới nhất</a>
          </span>
                    <a href='$base_url/phim-le/' class='read-more'>xem Thêm >></a>
                </div>
                <div class='mv-group'>";

                    foreach ($this->view->phim_le as $row){
                        $ten_film = ConvertKhongDau($row['ten_film']);
                    $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                    echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.2/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.2/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}

           echo'     </div>
            </div>
        </div>
    </section>
    <section class="movie">
        <div class="container">
            <div class="wrap-item">';
                echo "<div class='title-section'>
          <span>
          <a href='$base_url/phim-le/' class='see-more'>Phim chiếu rạp mới nhất</a>
          </span>
                    <a href='$base_url/phim-le/' class='read-more'>xem Thêm >></a>
                </div>
                <div class='mv-group'>";
                    foreach ($this->view->phim_chieu_rap as $row){
                        $ten_film = ConvertKhongDau($row['ten_film']);
                    $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                    echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.3/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.3/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}

        echo'</div>
            </div>
        </div>
    </section>
    <section class="movie">
        <div class="container">
            <div class="wrap-item">';
           echo "<div class='title-section'>
          <span>
          <a href='$base_url/hoat-hinh-anime/' class='see-more'>Hoạt hình mới nhất</a>
          </span>
                    <a href='$base_url/hoat-hinh-anime/' class='read-more'>xem Thêm >></a>
                </div>
                <div class='mv-group'>";
                    foreach ($this->view->phim_anime as $row){
                        $ten_film = ConvertKhongDau($row['ten_film']);
                    $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                    echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.4/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.4/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}

         echo"</div>
            </div>
        </div>
    </section>
</main>";

}