<link rel="stylesheet" href="<?php echo public_path;?>/css/phan_trang.css">
<section class="movie">
    <div class="container">
        <div class="wrap-item">
            <div class='title-section'>
          <span>
          <a href='' class='see-more'><?php
              $my_title = (string)$this->view->ten_quoc_gia;
              echo "<h1>$my_title</h1>"; ?></a>
          </span>
            </div>
            <div class='mv-group'>
                <?php
                $link_public = public_path;
                $phim = thong_tin_phim_path;
                $base_url = base_url;
                foreach ($this->view->quoc_gia as $row){
                    $ten_film = ConvertKhongDau($row['ten_film']);
                    $ten_film_english = ConvertKhongDau($row['ten_film_english']);
                    echo "<div class='mv-item'>
                <div class='mv-item-iner'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='img-item'>
                        <div class='mv-item-img' alt='{$row['ten_film']}' title='{$row['ten_film']} - {$row['ten_film_english']}' style='background: url({$row['link_anh']}) no-repeat scroll center top / cover;'>
                        </div>
                        <i class='btn-play'>
                            <img src='$base_url/publics/images/btn-play.png' alt='hgfilm - {$row['ten_film']} - {$row['ten_film_english']}' width='50'>
                        </i>
                    </a>
                    <span class='label'>Tập {$row['ten_tap']}</span>
                </div>
                <div class='mv-item-info'>
                    <a href='$phim/$ten_film-$ten_film_english-{$row['id_film']}.1/tap-{$row['ten_tap']}/' class='mv-title'>
                    {$row['ten_film']}
                    </a>
                </div>
            </div>";}

                ?>
            </div>
        </div>
    </div>
</section>
<div class="pagination">
    <?php
    //hiển thị phần phân trang
    // nếu current_page > 1 và total_page > 1 mới hiển thị nút prev
    $ten_quoc_gia = ConvertKhongDau($my_title);
    $data = '';
    if ($this->view->current_page > 1 && $this->view->total_page > 1){
        $data .= '<a class="phan_trang" href="'.$base_url.'/quoc-gia/'.$ten_quoc_gia.'-'.$_GET['id'].'/page-'.($this->view->current_page-1).'/">Prev</a>';
    }

    // Lặp khoảng giữa

    $data .=($this->view->current_page - 2) > 1 ? '<li class="phan_trang">...</li>' :'';
    for($i = ($this->view->current_page - 2) > 0 ? ($this->view->current_page - 2) : 1; $i <= (($this->view->current_page + 2) > $this->view->total_page ? $this->view->total_page :($this->view->current_page + 2)); $i++){
        if($i == $this->view->current_page){
            $data .= '<span class="phan_trang" style="background-color: white;color: black">'.$i.'</span>';
        } else{
            $data .= '<a class="phan_trang" href="'.$base_url.'/quoc-gia/'.$ten_quoc_gia.'-'.$_GET['id'].'/page-'.$i.'/">'.$i.'</a>';
        }
    }
    $data .=($this->view->current_page + 2) < $this->view->total_page ? '<li class="phan_trang">...</li>' :'';

    // nếu current_page < $this->view->total_page và total_page > 1 mới hiển thị nút prev
    if ($this->view->current_page < $this->view->total_page && $this->view->total_page > 1){
        $data .= '<a class="phan_trang" href="'.$base_url.'/quoc-gia/'.$ten_quoc_gia.'-'.$_GET['id'].'/page-'.($this->view->current_page+1).'/">Next</a>';
    }
    echo $data;
    ?>
</div>