<link rel="stylesheet" href="<?php echo public_path;?>/css/phan_trang.css">
<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title"><?php echo  $this->view->title; ?></h3>
              <a href="?controller=admin-chi-tiet-the-loai&action=add">Thêm mới</a>
            </div>
              <form action="" method="get">
                  <input type="hidden" name="controller" value ="admin-chi-tiet-the-loai">
                  <input type="text" name="search" placeholder="Nhập Tên phim Cần Tìm">
                  <input type="submit" value="search">
                  <a href="?controller=admin-dao-dien">Clear</a>
              </form>
            <!-- /.card-header -->
            <div class="card-body">
                <form action="" method="get">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                   <tr>
                            <th>ID</th>
                            <th>Tên Film</th>
                            <th>Tên Thể Loại</th>

                     </tr>
                </thead>
                <tbody>
                   <?php
                                foreach($this->view->list as $row){

                                    $link_edit = "<a href='?controller=admin-chi-tiet-the-loai&action=edit&id={$row['id']}'>{$row['ten_film']}</a>";
                                    echo " <tr>
                                                    <td>{$row['id']}</td>
                                                    <td>{$link_edit}</td>
                                                    <td>{$row['ten_the_loai']}</td>
                                                </tr>";
                                }

                    ?>
                </tbody>
                
              </table>
                    <div class="pagination">
                        <?php
                        //hiển thị phần phân trang
                        $base_url = base_url;
                        $ten_film="";
                        if (isset($_GET['search']) && strlen($_GET['search']) > 0) {
                            $ten_film = "&search=".$_GET['search'];
                        }
                        $url_admin = "?controller=admin-chi-tiet-the-loai$ten_film";
                        $data = '';
                        if ($this->view->current_page > 1 && $this->view->total_page > 1){
                            $data .= '<a class="phan_trang" href="'.$base_url.''.$url_admin.'&page='.($this->view->current_page-1).'">Prev</a>';
                        }

                        // Lặp khoảng giữa

                        $data .=($this->view->current_page - 3) > 1 ? '<li class="phan_trang">...</li>' :'';
                        for($i = ($this->view->current_page - 3) > 0 ? ($this->view->current_page - 3) : 1; $i <= (($this->view->current_page + 3) > $this->view->total_page ? $this->view->total_page :($this->view->current_page + 3)); $i++){
                            if($i == $this->view->current_page){
                                $data .= '<span class="phan_trang" style="background-color: white;color: black;border: 1px solid;">'.$i.'</span>';
                            } else{
                                $data .= '<a class="phan_trang" href="'.$url_admin.'&page='.$i.'">'.$i.'</a>';
                            }
                        }
                        $data .=($this->view->current_page + 3) < $this->view->total_page ? '<li class="phan_trang">...</li>' :'';

                        // nếu current_page < $this->view->total_page và total_page > 1 mới hiển thị nút prev
                        if ($this->view->current_page < $this->view->total_page && $this->view->total_page > 1){
                            $data .= '<a class="phan_trang" href="'.$url_admin.'&page='.($this->view->current_page+1).'">Next</a>';
                        }
                        echo $data;
                        ?>
                    </div>
                    <style type="text/css">
                        .phan_trang{
                            display: inline;
                        }
                    </style>
                </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>




