
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title><?php echo $this->layout->meta_des;?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <!-- Font Awesome -->
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
    <!-- Ionicons -->
    <link rel='stylesheet' href='https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'>
    <!-- Theme style -->
    <link rel='stylesheet' href='<?php echo base_url;?>/publics/template-admin/dist/css/adminlte.min.css'>
    <link rel='stylesheet' href='<?php echo base_url;?>/publics/template-admin/plugins/select2/select2.min.css'>
    <!-- Google Font: Source Sans Pro -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700' rel='stylesheet'>
    <script type="text/javascript" href='<?php echo base_url;?>/publics/template-admin/plugins/select2/select2.full.min.js'></script>
</head>
<body class='sidebar-collapse sidebar-mini'>
<!-- Site wrapper -->
<div class='wrapper'>
    <!-- Navbar -->
    <nav class='main-header navbar navbar-expand bg-white navbar-light border-bottom'>
        <!-- Left navbar links -->
        <ul class='navbar-nav'>
            <li class='nav-item'>
                <a class='nav-link' data-widget='pushmenu' href='#'><i class='fa fa-bars'></i></a>
            </li>
            <li class='nav-item d-none d-sm-inline-block'>
                <a href='?controller=admin&action=index' class='nav-link'>Home</a>
            </li>
            <li class='nav-item d-none d-sm-inline-block'>
                <a href='#' class='nav-link'>Contact</a>
            </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class='form-inline ml-3'>
            <div class='input-group input-group-sm'>
               
               
            </div>
        </form>

        <!-- Right navbar links -->
        <ul class='navbar-nav ml-auto'>
            <li><?php if(isset($_SESSION['auth'])){
                // đã đăng nhập\
                $userInfo = $_SESSION['auth'];

                echo "$userInfo->ho_ten ($userInfo->username)";
                echo "<a href='?controller=admin&action=logout'>Đăng Xuất </a>";
                }?>
            </li>
            <li class='nav-item dropdown'>
                <a class='nav-link' data-toggle='dropdown' href='#'>
                    <i class='fa fa-comments-o'></i>
                    <span class='badge badge-danger navbar-badge'>3</span>
                </a>
                <div class='dropdown-menu dropdown-menu-lg dropdown-menu-right'>
                    <a href='#' class='dropdown-item'>
                        <!-- Message Start -->
                        <div class='media'>
                            <img src='<?php echo base_url;?>/publics/template-admin/dist/img/user1-128x128.jpg' alt='User Avatar' class='img-size-50 mr-3 img-circle'>
                            <div class='media-body'>
                                <h3 class='dropdown-item-title'>
                                    Brad Diesel
                                    <span class='float-right text-sm text-danger'><i class='fa fa-star'></i></span>
                                </h3>
                                <p class='text-sm'>Call me whenever you can...</p>
                                <p class='text-sm text-muted'><i class='fa fa-clock-o mr-1'></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item'>
                        <!-- Message Start -->
                        <div class='media'>
                            <img src='<?php echo base_url;?>/publics/template-admin/dist/img/user8-128x128.jpg' alt='User Avatar' class='img-size-50 img-circle mr-3'>
                            <div class='media-body'>
                                <h3 class='dropdown-item-title'>
                                    John Pierce
                                    <span class='float-right text-sm text-muted'><i class='fa fa-star'></i></span>
                                </h3>
                                <p class='text-sm'>I got your message bro</p>
                                <p class='text-sm text-muted'><i class='fa fa-clock-o mr-1'></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item'>
                        <!-- Message Start -->
                        <div class='media'>
                            <img src='<?php echo base_url;?>/publics/template-admin/dist/img/user3-128x128.jpg' alt='User Avatar' class='img-size-50 img-circle mr-3'>
                            <div class='media-body'>
                                <h3 class='dropdown-item-title'>
                                    Nora Silvester
                                    <span class='float-right text-sm text-warning'><i class='fa fa-star'></i></span>
                                </h3>
                                <p class='text-sm'>The subject goes here</p>
                                <p class='text-sm text-muted'><i class='fa fa-clock-o mr-1'></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item dropdown-footer'>See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class='nav-item dropdown'>
                <a class='nav-link' data-toggle='dropdown' href='#'>
                    <i class='fa fa-bell-o'></i>
                    <span class='badge badge-warning navbar-badge'>15</span>
                </a>
                <div class='dropdown-menu dropdown-menu-lg dropdown-menu-right'>
                    <span class='dropdown-item dropdown-header'>15 Notifications</span>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item'>
                        <i class='fa fa-envelope mr-2'></i> 4 new messages
                        <span class='float-right text-muted text-sm'>3 mins</span>
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item'>
                        <i class='fa fa-users mr-2'></i> 8 friend requests
                        <span class='float-right text-muted text-sm'>12 hours</span>
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item'>
                        <i class='fa fa-file mr-2'></i> 3 new reports
                        <span class='float-right text-muted text-sm'>2 days</span>
                    </a>
                    <div class='dropdown-divider'></div>
                    <a href='#' class='dropdown-item dropdown-footer'>See All Notifications</a>
                </div>
            </li>
            <li class='nav-item'>
                <a class='nav-link' data-widget='control-sidebar' data-slide='true' href='#'>
                    <i class='fa fa-th-large'></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class='main-sidebar sidebar-dark-primary elevation-4'>
        <!-- Brand Logo -->
        <a href='<?php echo base_url;?>/publics/template-admin/index3.html' class='brand-link'>
            <img src='<?php echo base_url;?>/publics/template-admin/dist/img/AdminLTELogo.png'
                 alt='AdminLTE Logo'
                 class='brand-image img-circle elevation-3'
                 style='opacity: .8'>
            <span class='brand-text font-weight-light'>HG Film</span>
        </a>

        <!-- Sidebar -->
        <div class='sidebar'>
            <!-- Sidebar user (optional) -->
            <div class='user-panel mt-3 pb-3 mb-3 d-flex'>
                <div class='image'>
                    <img src='<?php echo base_url;?>/publics/template-admin/dist/img/user2-160x160.jpg' class='img-circle elevation-2' alt='User Image'>
                </div>
                <div class='info'>
                    <a href='#' class='d-block'><?php if(isset($_SESSION['auth'])){
                            // đã đăng nhập\
                            $userInfo = $_SESSION['auth'];

                            echo "$userInfo->username";
                        }?></a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class='mt-2'>
                <ul class='nav nav-pills nav-sidebar flex-column' data-widget='treeview' role='menu' data-accordion='false'>
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class='nav-item has-treeview'>
                        
                    </li>
                    
                    
                   
                    <li class='nav-item has-treeview'>
                        <a href='#' class='nav-link'>
                            <i class='nav-icon fa fa-table'></i>
                            <p>
                                Tables
                                <i class='fa fa-angle-left right'></i>
                            </p>
                        </a>
                        <ul class='nav nav-treeview'>
                            <li class='nav-item'>
                                <a href='?controller=admin-film&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Film</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-danh-muc&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Danh Mục</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-the-loai&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Thể loại</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-dien-vien&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Diễn Viên</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-dao-dien&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Đạo Diễn</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-quoc-gia&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Quốc Gia</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-nam-phat-hanh&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Năm Phát Hành</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-nguoi-dung&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Tài Khoản</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-user&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table User</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-slide&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Slide</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-banner-qc&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Banner</p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-chi-tiet-the-loai&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Chi Tiết Thể Loại </p>
                                </a>
                            </li>
                            <li class='nav-item'>
                                <a href='?controller=admin-tap-film&action=index' class='nav-link'>
                                    <i class='fa fa-circle-o nav-icon'></i>
                                    <p>Table Tập Film </p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-header'>EXAMPLES</li>

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class='content-wrapper'>
        <!-- Content Header (Page header) -->
        <section class='content-header'>
            <div class='container-fluid'>
                <div class='row mb-2'>
                    <div class='col-sm-6'>
                        <!-- <h1>
                            <?php
                            if(isset($this->layout->tieu_de_action))
                                echo $this->layout->tieu_de_action;
                            else
                                echo 'TRANG QUẢN TRỊ';
                            ?>
                        </h1> -->
                    </div>
                    <div class='col-sm-6'>
                        <ol class='breadcrumb float-sm-right'>
                            <li class='breadcrumb-item'><a href=''>Home</a></li>
                            <li class='breadcrumb-item active'>Blank Page</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class='content'>
        <?php $this->showContent();?>
 </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!--<footer class='main-footer'>
        <div class='float-right d-none d-sm-block'>
            <b>Version</b> 3.0.0-alpha
        </div>
        <strong>Copyright &copy; 2014-2018 <a href='http://adminlte.io'>AdminLTE.io</a>.</strong> All rights
        reserved.
    </footer>-->

    <!-- Control Sidebar -->
    <aside class='control-sidebar control-sidebar-dark'>
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src='<?php echo base_url;?>/publics/template-admin/plugins/jquery/jquery.min.js'></script>
<!-- Bootstrap 4 -->
<script src='<?php echo base_url;?>/publics/template-admin/plugins/bootstrap/js/bootstrap.bundle.min.js'></script>
<!-- SlimScroll -->
<script src='<?php echo base_url;?>/publics/template-admin/plugins/slimScroll/jquery.slimscroll.min.js'></script>
<!-- FastClick -->
<script src='<?php echo base_url;?>/publics/template-admin/plugins/fastclick/fastclick.js'></script>
<!-- AdminLTE App -->
<script src='<?php echo base_url;?>/publics/template-admin/dist/js/adminlte.min.js'></script>
<!-- AdminLTE for demo purposes -->
<script src='<?php echo base_url;?>/publics/template-admin/dist/js/demo.js'></script>
</body>
</html>



